import Web3 from 'web3';
const web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545/"));

// NOTE - These values are gonna change each time depending on testing environment
let account0 = '0x04444086FD65f507735a1f25E0103d29FD11E925';
let blockTracerABI = [{"constant":false,"inputs":[{"internalType":"string","name":"fullName","type":"string"},{"internalType":"string","name":"phone","type":"string"},{"internalType":"string","name":"location","type":"string"}],"name":"startTraceChain","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"internalType":"string","name":"fullName","type":"string"},{"internalType":"string","name":"phone","type":"string"},{"internalType":"string","name":"location","type":"string"},{"internalType":"bytes32","name":"chainId","type":"bytes32"}],"name":"joinChain","outputs":[{"internalType":"bool","name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"internalType":"string","name":"fullName","type":"string"},{"internalType":"string","name":"phone","type":"string"},{"internalType":"string","name":"location","type":"string"},{"internalType":"bool","name":"results","type":"bool"}],"name":"updateTestResults","outputs":[{"internalType":"bool","name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"internalType":"string","name":"fullName","type":"string"},{"internalType":"string","name":"phone","type":"string"},{"internalType":"string","name":"location","type":"string"}],"name":"getContactInfo","outputs":[{"internalType":"string","name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"internalType":"string","name":"fullName","type":"string"},{"internalType":"string","name":"phone","type":"string"},{"internalType":"string","name":"location","type":"string"}],"name":"getTraceChain","outputs":[{"internalType":"bytes32[]","name":"","type":"bytes32[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"internalType":"string","name":"fullName","type":"string"},{"internalType":"string","name":"phone","type":"string"},{"internalType":"string","name":"location","type":"string"}],"name":"getTestResults","outputs":[{"internalType":"bool","name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"internalType":"string","name":"fullName","type":"string"},{"internalType":"string","name":"phone","type":"string"},{"internalType":"string","name":"location","type":"string"}],"name":"getUniqueID","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"payable":false,"stateMutability":"view","type":"function"}];
let blockTracerAddress = '0x9669763fA3A89456e57a288a246aC034e309bCF5';

// Export to use in React app
const blockTracerContract = new web3.eth.Contract(blockTracerABI, blockTracerAddress);
export { blockTracerContract, account0};